version: '3.8'

services:
  are-reporting:
    build: .
    container_name: are-reporting-app
    ports:
      - "3000:3000"
    volumes:
      - are_data:/app/data
    environment:
      - NODE_ENV=production
      - JWT_SECRET=ihr_super_geheimnisvoller_schluessel
      - DB_PATH=/app/data/orders.db
    restart: always

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    container_name: are-reporting-oauth2-proxy
    ports:
      - "80:4180"
    environment:
      - OAUTH2_PROXY_PROVIDER=azure
      - OAUTH2_PROXY_CLIENT_ID=d1502a42-ba8d-4546-84cc-a2eb4a2e9cfd
      - OAUTH2_PROXY_CLIENT_SECRET=5ec3234e-cea9-4603-8844-cffbc7aac367
      - OAUTH2_PROXY_AZURE_TENANT=a65e00c7-7272-47aa-b3cf-26e459361ecf
      - OAUTH2_PROXY_OIDC_ISSUER_URL=https://login.microsoftonline.com/a65e00c7-7272-47aa-b3cf-26e459361ecf/v2.0
      - OAUTH2_PROXY_UPSTREAMS=http://are-reporting:3000/
      - OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180
      - OAUTH2_PROXY_REDIRECT_URL=http://10.101.53.7/oauth2/callback
      - OAUTH2_PROXY_COOKIE_SECRET=YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXoxMjM0NTY=
      - OAUTH2_PROXY_EMAIL_DOMAINS=*
      - OAUTH2_PROXY_COOKIE_SECURE=false
      - OAUTH2_PROXY_PASS_USER_HEADERS=true
    restart: always

volumes:
  are_data:
