version: '3.8'

services:
  are-reporting:
    build: .
    container_name: are-reporting-app
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      - JWT_SECRET=ihr_super_geheimnisvoller_schluessel
      - DB_PATH=/app/data/orders.db
    restart: always
